// <auto-generated />
using System;
using BSkyClone.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSkyClone.Migrations
{
    [DbContext(typeof(BSkyDbContext))]
    [Migration("20260122052505_AddBookmarksCountToPost")]
    partial class AddBookmarksCountToPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BSkyClone.Models.BlockedAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId", "BlockedUserId")
                        .HasName("PK__BlockedA__0A8170EB918D5838");

                    b.HasIndex("BlockedUserId");

                    b.ToTable("BlockedAccounts");
                });

            modelBuilder.Entity("BSkyClone.Models.Bookmark", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__Bookmark__8D29EA4D4F993AF5");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Bookmark__C451DB30DF335A92")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BSkyClone.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Conversa__3214EC0776FD5532");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("BSkyClone.Models.ConversationParticipant", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("PK__Conversa__112854B3CF95C0F9");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("BSkyClone.Models.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SubscribersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Feeds__3214EC0733EF47B5");

                    b.HasIndex("CreatorId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Feeds__C451DB30DDF6B147")
                        .IsUnique();

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("BSkyClone.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Interest__3214EC071202F311");

                    b.HasIndex(new[] { "Slug" }, "UQ__Interest__BC7B5FB60749EE1D")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("BSkyClone.Models.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__Likes__8D29EA4DA4FAA6F6");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Likes__C451DB30B024EDAB")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("BSkyClone.Models.LinkPreview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasFilter("[PostId] IS NOT NULL");

                    b.ToTable("LinkPreviews");
                });

            modelBuilder.Entity("BSkyClone.Models.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("social");

                    b.HasKey("Id")
                        .HasName("PK__Lists__3214EC07397CB41F");

                    b.HasIndex("OwnerId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("BSkyClone.Models.ListMember", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("ListId", "UserId")
                        .HasName("PK__ListMemb__32FBA4C18A09448F");

                    b.HasIndex("UserId");

                    b.ToTable("ListMembers");
                });

            modelBuilder.Entity("BSkyClone.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRecalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Messages__3214EC0740CF255F");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Messages__C451DB300D86D8F0")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BSkyClone.Models.MessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_MessageReactions");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("BSkyClone.Models.MutedAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MutedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId", "MutedUserId")
                        .HasName("PK__MutedAcc__2416C501D72C1110");

                    b.HasIndex("MutedUserId");

                    b.ToTable("MutedAccounts");
                });

            modelBuilder.Entity("BSkyClone.Models.MutedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__MutedWor__3214EC076609311A");

                    b.HasIndex("UserId");

                    b.ToTable("MutedWords");
                });

            modelBuilder.Entity("BSkyClone.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07E46938FE");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "RecipientId" }, "IX_Notifications_RecipientId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Notifica__C451DB3001D0607B")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BSkyClone.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<bool?>("AllowQuotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookmarksCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LikesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("QuotesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("RepliesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ReplyRestriction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("anyone");

                    b.Property<Guid?>("ReplyToPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RepostsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("RootPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC07CB992B89");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReplyToPostId");

                    b.HasIndex(new[] { "RootPostId" }, "IX_Posts_RootPostId");

                    b.HasIndex(new[] { "Tid" }, "IX_Posts_Tid");

                    b.HasIndex(new[] { "Tid" }, "UQ__Posts__C451DB308F8113F0")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BSkyClone.Models.PostMedium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__PostMedi__3214EC071ED49D5C");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("BSkyClone.Models.Repost", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__Reposts__8D29EA4D0BE60F6C");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "Tid" }, "UQ__Reposts__C451DB3010751B4E")
                        .IsUnique();

                    b.ToTable("Reposts");
                });

            modelBuilder.Entity("BSkyClone.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("FollowersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("FollowingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07B91FF525");

                    b.HasIndex(new[] { "Did" }, "IX_Users_Did");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E411906A34")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340284C248")
                        .IsUnique();

                    b.HasIndex(new[] { "Did" }, "UQ__Users__C0312219EBC0F5F8")
                        .IsUnique();

                    b.HasIndex(new[] { "Handle" }, "UQ__Users__FE5BB31A92C6FE6D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BSkyClone.Models.UserFeedSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PinnedOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "FeedId")
                        .HasName("PK__UserFeed__56D0A1B996CA0707");

                    b.HasIndex("FeedId");

                    b.ToTable("UserFeedSubscriptions");
                });

            modelBuilder.Entity("BSkyClone.Models.UserFollow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("FollowerId", "FollowingId")
                        .HasName("PK__UserFoll__79CB0335AE8EF105");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("BSkyClone.Models.UserListSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("PinnedOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "ListId")
                        .HasName("PK_UserListSubscription");

                    b.HasIndex("ListId");

                    b.ToTable("UserListSubscriptions");
                });

            modelBuilder.Entity("BSkyClone.Models.UserSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdultContentFilter")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("hide");

                    b.Property<string>("AppLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<bool?>("AutoplayVideoGif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("DefaultAllowQuotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DefaultReplyRestriction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("anyone");

                    b.Property<bool?>("EnableAdultContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("FontSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<bool?>("NotifyFollowers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("NotifyLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("NotifyReplies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("RequireAltText")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SortReplies")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("top");

                    b.Property<string>("ThemeMode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("system");

                    b.HasKey("UserId")
                        .HasName("PK__UserSett__1788CC4CA56EF176");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PostInterest", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "InterestId")
                        .HasName("PK__PostInte__C81A52DEA5818FC9");

                    b.HasIndex("InterestId");

                    b.ToTable("PostInterests", (string)null);
                });

            modelBuilder.Entity("PostReplyAllowedList", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "ListId")
                        .HasName("PK__PostRepl__E42A52989C4F35D5");

                    b.HasIndex("ListId");

                    b.ToTable("PostReplyAllowedLists", (string)null);
                });

            modelBuilder.Entity("UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "InterestId")
                        .HasName("PK__UserInte__7580FE8A5B5B0B2A");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests", (string)null);
                });

            modelBuilder.Entity("BSkyClone.Models.BlockedAccount", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "BlockedUser")
                        .WithMany("BlockedAccountBlockedUsers")
                        .HasForeignKey("BlockedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_BlockedUser");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("BlockedAccountUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BlockedOwner");

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.Bookmark", b =>
                {
                    b.HasOne("BSkyClone.Models.Post", "Post")
                        .WithMany("Bookmarks")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookmarkPost");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_BookmarkUser");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.ConversationParticipant", b =>
                {
                    b.HasOne("BSkyClone.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_CP_Conv");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CP_User");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.Feed", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "Creator")
                        .WithMany("Feeds")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_FeedCreator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BSkyClone.Models.Like", b =>
                {
                    b.HasOne("BSkyClone.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LikePost");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LikeUser");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.LinkPreview", b =>
                {
                    b.HasOne("BSkyClone.Models.Message", "Message")
                        .WithOne("LinkPreview")
                        .HasForeignKey("BSkyClone.Models.LinkPreview", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BSkyClone.Models.Post", "Post")
                        .WithOne("LinkPreview")
                        .HasForeignKey("BSkyClone.Models.LinkPreview", "PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Message");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BSkyClone.Models.List", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "Owner")
                        .WithMany("Lists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ListOwner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BSkyClone.Models.ListMember", b =>
                {
                    b.HasOne("BSkyClone.Models.List", "List")
                        .WithMany("ListMembers")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LM_List");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("ListMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LM_User");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.Message", b =>
                {
                    b.HasOne("BSkyClone.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_MsgConv");

                    b.HasOne("BSkyClone.Models.Message", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BSkyClone.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_MsgSender");

                    b.Navigation("Conversation");

                    b.Navigation("ReplyTo");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BSkyClone.Models.MessageReaction", b =>
                {
                    b.HasOne("BSkyClone.Models.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.MutedAccount", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "MutedUser")
                        .WithMany("MutedAccountMutedUsers")
                        .HasForeignKey("MutedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MutedUser");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("MutedAccountUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MutedOwner");

                    b.Navigation("MutedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.MutedWord", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("MutedWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MutedWordUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.Notification", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "Recipient")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK_NotifRecipient");

                    b.HasOne("BSkyClone.Models.User", "Sender")
                        .WithMany("NotificationSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_NotifSender");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BSkyClone.Models.Post", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostAuthor");

                    b.HasOne("BSkyClone.Models.Post", "ReplyToPost")
                        .WithMany("InverseReplyToPost")
                        .HasForeignKey("ReplyToPostId")
                        .HasConstraintName("FK_PostReply");

                    b.HasOne("BSkyClone.Models.Post", "RootPost")
                        .WithMany("InverseRootPost")
                        .HasForeignKey("RootPostId")
                        .HasConstraintName("FK_PostRoot");

                    b.Navigation("Author");

                    b.Navigation("ReplyToPost");

                    b.Navigation("RootPost");
                });

            modelBuilder.Entity("BSkyClone.Models.PostMedium", b =>
                {
                    b.HasOne("BSkyClone.Models.Post", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MediaPost");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BSkyClone.Models.Repost", b =>
                {
                    b.HasOne("BSkyClone.Models.Post", "Post")
                        .WithMany("Reposts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RepostPost");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("Reposts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RepostUser");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.UserFeedSubscription", b =>
                {
                    b.HasOne("BSkyClone.Models.Feed", "Feed")
                        .WithMany("UserFeedSubscriptions")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubsFeed");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany("UserFeedSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubsUser");

                    b.Navigation("Feed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.UserFollow", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "Follower")
                        .WithMany("UserFollowFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("FK_Follower");

                    b.HasOne("BSkyClone.Models.User", "Following")
                        .WithMany("UserFollowFollowings")
                        .HasForeignKey("FollowingId")
                        .IsRequired()
                        .HasConstraintName("FK_Following");

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("BSkyClone.Models.UserListSubscription", b =>
                {
                    b.HasOne("BSkyClone.Models.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ULS_List");

                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ULS_User");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BSkyClone.Models.UserSetting", b =>
                {
                    b.HasOne("BSkyClone.Models.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("BSkyClone.Models.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SettingsUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostInterest", b =>
                {
                    b.HasOne("BSkyClone.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PI_Interest");

                    b.HasOne("BSkyClone.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PI_Post");
                });

            modelBuilder.Entity("PostReplyAllowedList", b =>
                {
                    b.HasOne("BSkyClone.Models.List", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .IsRequired()
                        .HasConstraintName("FK_PRAL_List");

                    b.HasOne("BSkyClone.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRAL_Post");
                });

            modelBuilder.Entity("UserInterest", b =>
                {
                    b.HasOne("BSkyClone.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UI_Interest");

                    b.HasOne("BSkyClone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UI_User");
                });

            modelBuilder.Entity("BSkyClone.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BSkyClone.Models.Feed", b =>
                {
                    b.Navigation("UserFeedSubscriptions");
                });

            modelBuilder.Entity("BSkyClone.Models.List", b =>
                {
                    b.Navigation("ListMembers");
                });

            modelBuilder.Entity("BSkyClone.Models.Message", b =>
                {
                    b.Navigation("LinkPreview");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("BSkyClone.Models.Post", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("InverseReplyToPost");

                    b.Navigation("InverseRootPost");

                    b.Navigation("Likes");

                    b.Navigation("LinkPreview");

                    b.Navigation("PostMedia");

                    b.Navigation("Reposts");
                });

            modelBuilder.Entity("BSkyClone.Models.User", b =>
                {
                    b.Navigation("BlockedAccountBlockedUsers");

                    b.Navigation("BlockedAccountUsers");

                    b.Navigation("Bookmarks");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("Feeds");

                    b.Navigation("Likes");

                    b.Navigation("ListMembers");

                    b.Navigation("Lists");

                    b.Navigation("Messages");

                    b.Navigation("MutedAccountMutedUsers");

                    b.Navigation("MutedAccountUsers");

                    b.Navigation("MutedWords");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("NotificationSenders");

                    b.Navigation("Posts");

                    b.Navigation("Reposts");

                    b.Navigation("UserFeedSubscriptions");

                    b.Navigation("UserFollowFollowers");

                    b.Navigation("UserFollowFollowings");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
