export interface LanguageMetadata {
    code: string;
    nativeName: string;
    englishName: string;
}

export const APP_LANGUAGES: LanguageMetadata[] = [
    { code: 'en', nativeName: 'English', englishName: 'English' },
    { code: 'af', nativeName: 'Afrikaans', englishName: 'Afrikaans' },
    { code: 'sq', nativeName: 'Shqip', englishName: 'Albanian' },
    { code: 'am', nativeName: 'አማርኛ', englishName: 'Amharic' },
    { code: 'ar', nativeName: 'العربية', englishName: 'Arabic' },
    { code: 'hy', nativeName: 'Հայերեն', englishName: 'Armenian' },
    { code: 'as', nativeName: 'অসমীয়া', englishName: 'Assamese' },
    { code: 'az', nativeName: 'Azərbaycanca', englishName: 'Azerbaijani' },
    { code: 'eu', nativeName: 'euskara', englishName: 'Basque' },
    { code: 'be', nativeName: 'Беларуская', englishName: 'Belarusian' },
    { code: 'bn', nativeName: 'বাংলা', englishName: 'Bangla' },
    { code: 'bg', nativeName: 'Български', englishName: 'Bulgarian' },
    { code: 'ca', nativeName: 'català', englishName: 'Catalan' },
    { code: 'zh-CN', nativeName: '简体中文', englishName: 'Simplified Chinese' },
    { code: 'zh-TW', nativeName: '繁體中文', englishName: 'Traditional Chinese' },
    { code: 'zh-HK', nativeName: '粵語 (香港)', englishName: 'Cantonese (HK)' },
    { code: 'hr', nativeName: 'Hrvatski', englishName: 'Croatian' },
    { code: 'cs', nativeName: 'Čeština', englishName: 'Czech' },
    { code: 'da', nativeName: 'dansk', englishName: 'Danish' },
    { code: 'nl', nativeName: 'Nederlands', englishName: 'Dutch' },
    { code: 'en-GB', nativeName: 'British English', englishName: 'British English' },
    { code: 'et', nativeName: 'eesti', englishName: 'Estonian' },
    { code: 'fa', nativeName: 'فارسی', englishName: 'Persian' },
    { code: 'fi', nativeName: 'suomi', englishName: 'Finnish' },
    { code: 'fr', nativeName: 'français', englishName: 'French' },
    { code: 'ka', nativeName: 'ქართული', englishName: 'Georgian' },
    { code: 'de', nativeName: 'Deutsch', englishName: 'German' },
    { code: 'el', nativeName: 'Ελληνικά', englishName: 'Greek' },
    { code: 'gu', nativeName: 'ગુજરાતી', englishName: 'Gujarati' },
    { code: 'he', nativeName: 'עברית', englishName: 'Hebrew' },
    { code: 'hi', nativeName: 'हिन्दी', englishName: 'Hindi' },
    { code: 'hu', nativeName: 'magyar', englishName: 'Hungarian' },
    { code: 'is', nativeName: 'íslenska', englishName: 'Icelandic' },
    { code: 'id', nativeName: 'Bahasa Indonesia', englishName: 'Indonesian' },
    { code: 'it', nativeName: 'italiano', englishName: 'Italian' },
    { code: 'ja', nativeName: '日本語', englishName: 'Japanese' },
    { code: 'kn', nativeName: 'ಕನ್ನಡ', englishName: 'Kannada' },
    { code: 'kk', nativeName: 'Қазақ тілі', englishName: 'Kazakh' },
    { code: 'km', nativeName: 'ភាសាខ្មែរ', englishName: 'Khmer' },
    { code: 'ko', nativeName: '한국어', englishName: 'Korean' },
    { code: 'lv', nativeName: 'latviešu', englishName: 'Latvian' },
    { code: 'lt', nativeName: 'lietuvių', englishName: 'Lithuanian' },
    { code: 'ml', nativeName: 'മലയാളം', englishName: 'Malayalam' },
    { code: 'mr', nativeName: 'मराठी', englishName: 'Marathi' },
    { code: 'ne', nativeName: 'नेपाली', englishName: 'Nepali' },
    { code: 'no', nativeName: 'Norsk', englishName: 'Norwegian' },
    { code: 'pa', nativeName: 'ਪੰਜਾਬੀ', englishName: 'Punjabi' },
    { code: 'pl', nativeName: 'polski', englishName: 'Polish' },
    { code: 'pt-BR', nativeName: 'português do Brasil', englishName: 'Brazilian Portuguese' },
    { code: 'pt-PT', nativeName: 'português europeu', englishName: 'European Portuguese' },
    { code: 'ro', nativeName: 'română', englishName: 'Romanian' },
    { code: 'ru', nativeName: 'русский', englishName: 'Russian' },
    { code: 'sk', nativeName: 'Slovenčina', englishName: 'Slovak' },
    { code: 'sl', nativeName: 'slovenščina', englishName: 'Slovenian' },
    { code: 'es', nativeName: 'español', englishName: 'Spanish' },
    { code: 'sv', nativeName: 'svenska', englishName: 'Swedish' },
    { code: 'ta', nativeName: 'தமிழ்', englishName: 'Tamil' },
    { code: 'te', nativeName: 'తెలుగు', englishName: 'Telugu' },
    { code: 'th', nativeName: 'ภาษาไทย', englishName: 'Thai' },
    { code: 'tr', nativeName: 'Türkçe', englishName: 'Turkish' },
    { code: 'uk', nativeName: 'українська', englishName: 'Ukrainian' },
    { code: 'ur', nativeName: 'اردو', englishName: 'Urdu' },
    { code: 'uz', nativeName: 'Oʻzbekcha', englishName: 'Uzbek' },
    { code: 'vi', nativeName: 'Tiếng Việt', englishName: 'Vietnamese' },
];

export const ALL_LANGUAGES: LanguageMetadata[] = [
    ...APP_LANGUAGES,
    { code: 'aa', nativeName: 'Afar', englishName: 'Afar' },
    { code: 'ab', nativeName: 'Abkhazian', englishName: 'Abkhazian' },
    { code: 'af', nativeName: 'Afrikaans', englishName: 'Afrikaans' },
    { code: 'ak', nativeName: 'Akan', englishName: 'Akan' },
    { code: 'sq', nativeName: 'Albanian', englishName: 'Albanian' },
    { code: 'am', nativeName: 'Amharic', englishName: 'Amharic' },
    { code: 'ar', nativeName: 'Arabic', englishName: 'Arabic' },
    { code: 'hy', nativeName: 'Armenian', englishName: 'Armenian' },
    { code: 'as', nativeName: 'Assamese', englishName: 'Assamese' },
    { code: 'av', nativeName: 'Avaric', englishName: 'Avaric' },
    { code: 'ae', nativeName: 'Avestan', englishName: 'Avestan' },
    { code: 'ay', nativeName: 'Aymara', englishName: 'Aymara' },
    { code: 'az', nativeName: 'Azerbaijani', englishName: 'Azerbaijani' },
    { code: 'ba', nativeName: 'Bashkir', englishName: 'Bashkir' },
    { code: 'bm', nativeName: 'Bambara', englishName: 'Bambara' },
    { code: 'be', nativeName: 'Belarusian', englishName: 'Belarusian' },
    { code: 'bn', nativeName: 'Bangla', englishName: 'Bangla' },
    // Adding more common ones to reach a substantial list similar to BlueSky
    { code: 'bg', nativeName: 'Bulgarian', englishName: 'Bulgarian' },
    { code: 'my', nativeName: 'Burmese', englishName: 'Burmese' },
    { code: 'et', nativeName: 'Estonian', englishName: 'Estonian' },
    { code: 'gu', nativeName: 'Gujarati', englishName: 'Gujarati' },
    { code: 'he', nativeName: 'Hebrew', englishName: 'Hebrew' },
    { code: 'hr', nativeName: 'Croatian', englishName: 'Croatian' },
    { code: 'is', nativeName: 'Icelandic', englishName: 'Icelandic' },
    { code: 'ka', nativeName: 'Georgian', englishName: 'Georgian' },
    { code: 'kk', nativeName: 'Kazakh', englishName: 'Kazakh' },
    { code: 'kn', nativeName: 'Kannada', englishName: 'Kannada' },
    { code: 'ky', nativeName: 'Kyrgyz', englishName: 'Kyrgyz' },
    { code: 'la', nativeName: 'Latin', englishName: 'Latin' },
    { code: 'lv', nativeName: 'Latvian', englishName: 'Latvian' },
    { code: 'lt', nativeName: 'Lithuanian', englishName: 'Lithuanian' },
    { code: 'ml', nativeName: 'Malayalam', englishName: 'Malayalam' },
    { code: 'mr', nativeName: 'Marathi', englishName: 'Marathi' },
    { code: 'pa', nativeName: 'Punjabi', englishName: 'Punjabi' },
    { code: 'fa', nativeName: 'Persian', englishName: 'Persian' },
    { code: 'sl', nativeName: 'Slovenian', englishName: 'Slovenian' },
    { code: 'sw', nativeName: 'Swahili', englishName: 'Swahili' },
    { code: 'ta', nativeName: 'Tamil', englishName: 'Tamil' },
    { code: 'te', nativeName: 'Telugu', englishName: 'Telugu' },
    { code: 'ur', nativeName: 'Urdu', englishName: 'Urdu' },
    { code: 'uz', nativeName: 'Uzbek', englishName: 'Uzbek' },
].sort((a, b) => a.englishName.localeCompare(b.englishName));
